# Generated by Django 3.0.3 on 2020-04-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approve',
            field=models.BooleanField(default=False, verbose_name='Publish Post'),
            preserve_default=False,
        ),
    ]
