# Generated by Django 3.0.3 on 2020-04-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
