# Generated by Django 3.0.3 on 2020-04-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20200417_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=True, upload_to='media/', verbose_name='Images'),
            preserve_default=False,
        ),
    ]
