# Generated by Django 3.0.3 on 2020-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20200417_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Images'),
        ),
    ]
