# Generated by Django 3.0.3 on 2020-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20200417_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secim',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
