# Generated by Django 3.0.3 on 2020-04-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_product_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='role',
        ),
    ]
