# Generated by Django 3.0.3 on 2020-04-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_product_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR')], default='admin', max_length=10),
        ),
    ]
