# Generated by Django 3.0.3 on 2020-04-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
