# Generated by Django 3.0.3 on 2020-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_product_bonus_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email_address',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_number',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
