# Generated by Django 3.0.3 on 2020-04-19 17:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_auto_20200419_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=ckeditor.fields.RichTextField(default=True),
            preserve_default=False,
        ),
    ]
