# Generated by Django 3.0.3 on 2020-04-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200416_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='published_date',
        ),
    ]
