# Generated by Django 3.0.3 on 2020-04-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_product_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lostorfound',
            field=models.BooleanField(choices=[(True, 'Lost'), (False, 'Found')], default=False),
            preserve_default=False,
        ),
    ]
