# Generated by Django 3.0.3 on 2020-04-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
