# Generated by Django 3.0.3 on 2020-04-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Product Name'),
        ),
    ]
