# Generated by Django 3.0.3 on 2020-04-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20200419_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='role',
        ),
    ]
