# Generated by Django 3.0.3 on 2020-04-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus_ammount',
            field=models.IntegerField(default=True, max_length=5),
            preserve_default=False,
        ),
    ]
