# Generated by Django 3.0.3 on 2020-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_auto_20200419_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('contact_number', models.IntegerField(null=True)),
                ('support_email', models.EmailField(max_length=40, null=True)),
                ('footer_info', models.CharField(max_length=100)),
            ],
        ),
    ]
