# Generated by Django 3.0.5 on 2020-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approve',
            field=models.BooleanField(default=False, verbose_name='Publish Post'),
        ),
    ]
