# Generated by Django 3.0.5 on 2020-05-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='lostorfound',
            field=models.BooleanField(choices=[(True, 'Get'), (False, 'Getme')], default=False, verbose_name='get?/getme?'),
        ),
    ]
