# Generated by Django 3.0.5 on 2020-05-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_test_lostorfound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='lostorfound',
            field=models.BooleanField(choices=[(True, 'Get'), (False, 'Getme')], verbose_name='get?/getme?'),
        ),
    ]
