# Generated by Django 3.0.5 on 2020-05-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_auto_20200502_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fast_service',
        ),
    ]
