# Generated by Django 3.0.5 on 2020-05-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_remove_product_fast_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='resm',
            field=models.ImageField(default=False, upload_to='', verbose_name='elave sekiller'),
            preserve_default=False,
        ),
    ]
