# Generated by Django 3.0.5 on 2020-05-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_product_resm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
