# Generated by Django 3.0.5 on 2020-05-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='resm',
            new_name='image',
        ),
    ]
