# Generated by Django 3.0.5 on 2020-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_auto_20200505_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='footer_image',
            field=models.ImageField(default=True, upload_to='', verbose_name='Footer image'),
            preserve_default=False,
        ),
    ]
