# Generated by Django 3.0.3 on 2020-04-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_register_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
